GET http://localhost:3003/api/blogs/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MTYyNTlhYjAyZDBmZTQzMTU2YjQ1ZjEiLCJpYXQiOjE2MzQ2MDYzOTksImV4cCI6MTYzNDYwOTk5OX0.FBD8IxYS3dn2E7WuIM7n2OVIp-TjQ6ol5Gvop-I1tIg

###

POST http://localhost:3003/api/blogs/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxNWQxNTgwNTdkZGJjY2Q2MWE2MWMzYyIsImlhdCI6MTYzMzUwMjc0MSwiZXhwIjoxNjMzNTA2MzQxfQ.nzVtYUwzDt6tNJnh9hNUPZ-V8QGRxw3JLoM-DVOYzms

{
    "title": "Dubai is awesome!",
    "author": "JJ",
    "url": "http://jj.com",
    "likes": 10
}

###

POST http://localhost:3003/api/blogs/
content-type: application/json

{
    "author": "JJ"
}

###

DELETE  http://localhost:3003/api/blogs/615eeaa01f7a72e93f485462
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MTYyNDEwMTUzZTU0MjMwMzM2NGUzNDEiLCJpYXQiOjE2MzM4MzM3ODUsImV4cCI6MTYzMzgzNzM4NX0.moNQBj76epEh8hfFW7LETwtLEqRhXLEOjopqxi82WpQ

